apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: infrastructure
  source:
    repoURL: https://github.com/SchulteMK/kube-cluster.git
    path: definitions/argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
