apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-bgp
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: infrastructure
  source:
    repoURL: https://github.com/SchulteMK/kube-cluster.git
    path: definitions/cilium-bgp
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
