apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: infrastructure
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: 'https://kubernetes-sigs.github.io/external-dns/'
    targetRevision: 1.14.5
    chart: external-dns
    helm:
      valuesObject:
        provider: 
          name: cloudflare
        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api
                key: apiKey
  - repoURL: https://github.com/SchulteMK/kube-cluster.git
    targetRevision: HEAD
    path: definitions/external-dns
