apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: infrastructure
  destination:
    name: in-cluster
    namespace: longhorn-system
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.6.2
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
