apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: infrastructure
  destination:
    name: in-cluster
    namespace: openebs
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://openebs.github.io/openebs
    chart: openebs
    targetRevision: 4.1.0
    helm:
      parameters:
        - name: engines.replicated.mayastor.enabled
          value: 'false'
