apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: infrastructure
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    chart: sealed-secrets
    targetRevision: 2.16.0
    helm:
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
