apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server
  namespace: argocd
spec:
  secretName: argocd-server-tls

  usages:
    - server auth
    #- client auth

  dnsNames:
    - argo.kocks.info

  issuerRef:
    kind: ClusterIssuer
    name: acme-prod
