apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/SchulteMK/kube-cluster.git
    path: definitions/argocd-applications
    targetRevision: HEAD
